### ISSUE TITLE
Where's my model?

### ISSUE THREAD

**Issue by bdeboe** [yurimarx/integratedml-wizard#2]
I'm not sure I'm expecting something that's just not there / ready yet, but was wondering what happens when I press the "Save" button in the model definition screen. It doesn't seem like my IntegratedML model is created in the target database (doesn't show up in INFORMATION_SCHEMA.ML_MODELS). I didn't see any error messages in the console.
 
Also, I can't _retrieve_ a model after creating it through the GUI. It's true that IntegratedML also doesn't let you alter models :-), but being able to find back what you defined and (one fine day?) issue a TRAIN command from the GUI sounds like a key feature.

Thanks!
benjamin

**Comment by yurimarx** [comment]
I see these errors here Benjamin. I will release the fixes today late.

Sorry by errors, 

And thanks to test.

Yuri

**Comment by yurimarx** [comment]
Bugs resolved! Train from GUI will be released tomorrow 07-14-2020.

**Comment by bdeboe** [comment]
great, thanks for the lightning-fast resolution!

**Comment by yurimarx** [comment]
> great, thanks for the lightning-fast resolution!

Now training feature is available
